export const rackets = [
  {
    id: 1,
    name: "Wilson Pro Staff 97 v14",
    imageUrl: "http://localhost:4000/Wilson-Pro-Staff-97-v14.jpg",
    price: 259,
    type: "racket",
    model: "Pro Staff 97",
    year: 2023,
    top10: true,
    description:
      "Классическая ракетка Wilson Pro Staff 97 v14 с отличным контролем и мощностью. Идеальна для игроков, ценящих точность и стабильность.",
    brandId: 1,
    brand: {
      id: 1,
      name: "Wilson",
    },
    userData: null,
  },
  {
    id: 2,
    name: "Wilson Blade 98 v8",
    imageUrl: "http://localhost:4000/Wilson-Blade-98-v8.jpg",
    price: 249,
    type: "racket",
    model: "Blade 98",
    year: 2022,
    top10: true,
    description:
      "Wilson Blade 98 v8 — агрессивная ракетка с отличной маневренностью и мощным ударом. Подходит для атакующих игроков.",
    brandId: 1,
    brand: {
      id: 1,
      name: "Wilson",
    },
    userData: null,
  },
  {
    id: 4,
    name: "Wilson Ultra 100 v4",
    imageUrl: "http://localhost:4000/Wilson-Ultra-100-v4.jpg",
    price: 229,
    type: "racket",
    model: "Ultra 100",
    year: 2022,
    top10: true,
    description:
      "Wilson Ultra 100 v4 — ракетка для мощных ударов с отличной скоростью. Отлично подходит для агрессивного стиля игры.",
    brandId: 1,
    brand: {
      id: 1,
      name: "Wilson",
    },
    userData: null,
  },
  {
    id: 9,
    name: "Head Speed MP 2024",
    imageUrl: "http://localhost:4000/Head-Speed-MP-2024.jpg",
    price: 269,
    type: "racket",
    model: "Speed MP",
    year: 2024,
    top10: true,
    description:
      "Head Speed MP 2024 — универсальная ракетка с отличной скоростью и контролем. Подходит для игроков всех уровней.",
    brandId: 2,
    brand: {
      id: 2,
      name: "Head",
    },
    userData: null,
  },
  {
    id: 10,
    name: "Head Speed Pro 2024",
    imageUrl: "http://localhost:4000/Head-Speed-Pro-2024.jpg",
    price: 279,
    type: "racket",
    model: "Speed Pro",
    year: 2024,
    top10: true,
    description:
      "Head Speed Pro 2024 — профессиональная ракетка с максимальной мощностью и точностью ударов. Идеальна для агрессивных игроков.",
    brandId: 2,
    brand: {
      id: 2,
      name: "Head",
    },
    userData: null,
  },
  {
    id: 13,
    name: "Head Extreme MP 2023",
    imageUrl: "http://localhost:4000/Head-Extreme-MP-2023.jpg",
    price: 259,
    type: "racket",
    model: "Extreme MP",
    year: 2023,
    top10: true,
    description:
      "Head Extreme MP 2023 предлагает мощь и вращение, идеально подходя для агрессивных игроков, любящих атакующий стиль.",
    brandId: 2,
    brand: {
      id: 2,
      name: "Head",
    },
    userData: null,
  },
  {
    id: 15,
    name: "Yonex Ezone 98 2024",
    imageUrl: "http://localhost:4000/Yonex-Ezone-98-2024.jpg",
    price: 265,
    type: "racket",
    model: "Ezone 98",
    year: 2024,
    top10: true,
    description:
      "Yonex Ezone 98 2024 — ракетка с отличной мощностью и контролем, созданная для игроков среднего и продвинутого уровня.",
    brandId: 3,
    brand: {
      id: 3,
      name: "Yonex",
    },
    userData: null,
  },
  {
    id: 17,
    name: "Yonex VCore Pro 97 2023",
    imageUrl: "http://localhost:4000/Yonex-VCore-Pro-97-2023.jpg",
    price: 275,
    type: "racket",
    model: "VCore Pro 97",
    year: 2023,
    top10: true,
    description:
      "Yonex VCore Pro 97 2023 — профессиональная ракетка с точным контролем и мощным ударом. Отличный выбор для соревновательных игроков.",
    brandId: 3,
    brand: {
      id: 3,
      name: "Yonex",
    },
    userData: null,
  },
  {
    id: 21,
    name: "Babolat Pure Drive 2024",
    imageUrl: "http://localhost:4000/Babolat-Pure-Drive-2024.jpg",
    price: 230,
    type: "racket",
    model: "Pure Drive",
    year: 2024,
    top10: true,
    description:
      "Babolat Pure Drive 2024 — одна из самых популярных ракеток, обеспечивающая мощь и точность ударов.",
    brandId: 4,
    brand: {
      id: 4,
      name: "Babolat",
    },
    userData: null,
  },
  {
    id: 28,
    name: "Babolat Pure Aero Rafa 2024",
    imageUrl: "http://localhost:4000/Babolat-Pure-Aero-Rafa-2024.jpg",
    price: 270,
    type: "racket",
    model: "Pure Aero Rafa",
    year: 2024,
    top10: true,
    description:
      "Babolat Pure Aero Rafa 2024 — специальная версия с улучшенным вращением и мощностью, вдохновленная Рафаэлем Надалем.",
    brandId: 4,
    brand: {
      id: 4,
      name: "Babolat",
    },
    userData: null,
  },
];
